language: python
#python:
#  - "2.7"
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=flake8
script:
  - tox
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
